const LB_CO2_EMMITED_BASE_PER_MILE = 0.845;

//
const LB_CO2_SAVE_PER_MILE_CARPOOL_PER_PERSON = 0.845;
const MINIMUM_PEOPLE_CARPOOL = 2;

//
const LB_CO2_SAVE_PER_MILE_SHUTTLE_PER_PERSON = 0.845;
const MINIMUM_PEOPLE_SHUTTLE = 3;

//
const MILE_LB_CO2_REDUX_WALK = 0.845;
const MILE_LB_CO2_REDUX_BIKE = 0.845;
const MILE_LB_CO2_REDUX_SCOOTER = 0.845;

const double AVG_SECS_MILE_CAR = 100;
const double AVG_SECS_MILE_WALK = 900;
const double AVG_SECS_MILE_BIKE_SCOOTER = 200; // car takes less than 240 secs
